name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create icon
      run: |
        python -c "
        from PIL import Image, ImageDraw
        import os
        os.makedirs('assets', exist_ok=True)
        size = (64, 64)
        image = Image.new('RGBA', size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(image)
        draw.rectangle([8, 6, 56, 58], outline='black', fill='white', width=2)
        draw.rectangle([20, 2, 44, 10], outline='black', fill='silver', width=1)
        draw.rectangle([22, 4, 42, 8], outline='black', fill='white', width=1)
        draw.line([14, 18, 50, 18], fill='black', width=2)
        draw.line([14, 26, 47, 26], fill='black', width=2)
        draw.line([14, 34, 44, 34], fill='black', width=2)
        draw.line([14, 42, 40, 42], fill='black', width=2)
        image.save('assets/icon.ico', format='ICO', sizes=[(64, 64), (32, 32), (16, 16)])
        print('Icon created successfully')
        "
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --noconfirm clipboard_manager.spec
        
    - name: Create portable package
      run: |
        python build.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ClipboardManager-Windows
        path: |
          dist/ClipboardManager.exe
          dist/ClipboardManager_v1.0_Portable.zip